### ISSUE TITLE
Link to sponsor users from Ethics page?

### ISSUE THREAD

**Issue by sstrubberg** [IBM-Design/idr#40]
![image](https://user-images.githubusercontent.com/15822070/60918629-6a41d880-a259-11e9-9256-b45c4f196d78.png)

**Comment by eleanorbartosh** [comment]
Let's have the copy be a second paragraph under "Preserve and strengthen client relationships" that says:

"One way to formalize this process is with a Sponsor User Program (link to new page you're making). Sponsor Users are a core part of Enterprise Design Thinking (link) and IBM Design Research, and help us design experiences for real target users rather than assumed needs. You can read more about Sponsor User Programs, including how to start and run one, below."

Then, can you use the small card style, @sstrubberg like you do on 5 Whys? (Or is that only for external links?)

Title for Small box: 
Sponsor User Program

**Comment by sstrubberg** [comment]
![image](https://user-images.githubusercontent.com/15822070/61064315-2836a500-a3c7-11e9-9ebd-a01b1c907ff2.png)

**Comment by eleanorbartosh** [comment]
approved
