### ISSUE TITLE
Accordion component: chevron should stay align with first line even in two liners

### ISSUE THREAD

**Issue by mjabbink** [IBM-Design/idr#98]
@alisonjoseph 
This is the same component used in brand center https://www.ibm.com/brand/help/faq

I believe AKQA documented that detail or maybe already included in Gatsby theme accordion

**Comment by alisonjoseph** [comment]
Just wanted to confirm this as a design change in the theme since the Carbon accordion centers the chevron. @jeanservaas 

Screen shot w/ added text from http://react.carbondesignsystem.com/?path=/story/accordion--default
<img width="520" alt="Screen Shot 2019-08-05 at 7 55 52 AM" src="https://user-images.githubusercontent.com/2753488/62466254-87819e00-b756-11e9-978e-ca90798d47ec.png">

**Comment by mjabbink** [comment]
Should be Carbon, not theme. It’s how it should be done across the board. It was originally specified this way but not implemented.

**Comment by alisonjoseph** [comment]
created an issue in the theme repo https://github.com/carbon-design-system/gatsby-theme-carbon/issues/305

**Comment by mjabbink** [comment]
Carbon core 14px component should behave the same way too.

**Comment by jnm2377** [comment]
Per @mjabbink comment:

> Should be Carbon, not theme. It’s how it should be done across the board. It was originally specified this way but not implemented.

Should this issue be moved to the carbon monorepo?

**Comment by alisonjoseph** [comment]
@jnm2377 yes 👍 I'll transfer
